- name: gather ec2 facts for later
  ec2_metadata_facts:

- name: see if we have a key
  become: True
  stat: path="/etc/mosquitto/certs/{{ mqtt_server_identity }}.key"
  register: key_file

- name: create our key if needed
  local_action: shell cd {{ role_path }}/files && openssl genrsa -out {{ mqtt_server_identity }}.key 2048
  when: not key_file.stat.exists

- name: see if we have a cert
  become: True
  stat: path="/etc/mosquitto/certs/{{ mqtt_server_identity }}.crt"
  register: cert_file

###
### WARNING!!!!! WARNING!!!!! WARNING!!!!
###
### this is poor security - putting passphrase in the code
### we should be using Ansible Vault to at least encrypt the values
###
- name: create our openssl config
  local_action:
    module: template
    dest: "{{ role_path }}/files/openssl.conf"
    src: "13_openssl.conf"
  when: not key_file.stat.exists or not cert_file.stat.exists

- name: create our cert if needed
  local_action: shell cd {{ role_path }}/files && openssl req -out {{ mqtt_server_identity }}.csr -key {{ mqtt_server_identity }}.key -new -subj "/C=US/ST=Ohio/L=Cleveland/O=CWRU/CN={{ ansible_ec2_public_hostname }}/emailAddress=nab2@cwru.edu" -config openssl.conf -sha256 && openssl x509 -req -in {{ mqtt_server_identity }}.csr -CA lampi_ca.crt -CAkey lampi_ca.key -CAcreateserial -out {{ mqtt_server_identity }}.crt -days 365 -sha256 -passin pass:iot12345 -extfile openssl.conf -extensions v3_req
  when: not key_file.stat.exists or not cert_file.stat.exists

- name: install our key (if needed)
  become: True
  copy:
    src: "{{ mqtt_server_identity }}.key"
    dest: /etc/mosquitto/certs/{{ mqtt_server_identity }}.key
  when: not key_file.stat.exists

- name: install our cert (if needed)
  become: True
  copy:
    src: "{{ mqtt_server_identity }}.crt"
    dest: /etc/mosquitto/certs/{{ mqtt_server_identity }}.crt
  when: not key_file.stat.exists or not cert_file.stat.exists


- name: install our CA
  become: True
  copy:
    src: lampi_ca.crt
    dest: /etc/mosquitto/ca_certificates/lampi_ca.crt

- name: install MQTT bridge configuration (updated for TLS)
  become: True
  template:
    src: 13_mqtt_port.conf
    dest: /etc/mosquitto/conf.d/port.conf

- name: restart mosquitto
  become: True
  service:
    name: mosquitto
    state: restarted
